name: text to md 
run-name: ${{github.actor}} is running convertor.
on: [push]
jobs:
  Setup-Java-JDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: jdk
      - run: java -v
