name: text to md 
run-name: ${{github.actor}} is running convertor.
on: [push]
jobs:
  Setup-Java-JDK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Using external action
        uses: sidsriedu/readme-genererator-action@main
      
