name: text to md 
run-name: ${{github.actor}} is running convertor.
on: [push]
jobs:
  Setup-Java-JDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java -version
