name: text to md 
run-name: ${{github.actor}} is running convertor.
on: [push]
jobs:
  Setup-Java-JDK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: java -version
      - run: javac TextToMDConvertor.java
      - run: java TextToMDConvertor
      
