name: text to md 
run-name: ${{github.actor}} is running convertor.
on: [push]
jobs:
  Setup-Java-JDK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Updating Readme
        run: |
          javac TextToMDConvertor.java
          java TextToMDConvertor
      - name: Git Push
        run: |
          git add .
          git commit -m "Updating Readme.md"
          git push
      
